---
deployment:
  tasks:
    - export DEPLOY_ENV=production

    - /bin/mkdir -p /tmp/cpanel-deploy

    - /bin/cp -r . /tmp/cpanel-deploy

    - cd /tmp/cpanel-deploy

    # Set proper permissions
    - /bin/chmod -R 755 storage
    - /bin/chmod -R 755 bootstrap/cache

    # Install dependencies
    - /usr/local/bin/composer install --no-dev --optimize-autoloader

    # Build assets if package.json exists
    - /usr/local/bin/npm ci
    - /usr/local/bin/npm run build

    # Run database migrations
    - /usr/local/bin/php artisan migrate --force

    # Seed database if needed
    - /usr/local/bin/php artisan db:seed --force

    # Optimize for production
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache

    # Create storage link
    - /usr/local/bin/php artisan storage:link

    # Clear caches
    - /usr/local/bin/php artisan cache:clear
    - /usr/local/bin/php artisan config:clear

    # Set final permissions
    - /bin/chmod -R 755 storage
    - /bin/chmod -R 755 bootstrap/cache

    # Copy to final location
    - /bin/cp -r /tmp/cpanel-deploy/* /home/$CPANEL_USERNAME/public_html

    # Clean up
    - /bin/rm -rf /tmp/cpanel-deploy
