[build]
  command = "php artisan config:clear && php artisan view:clear && php artisan route:clear && npm install && npm run build"
  publish = "public"

[build.environment]
  PHP_VERSION = "8.1"
  COMPOSER_VERSION = "2.5.8"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
