services:
  - type: web
    name: palsa-pos
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan migrate --force
      php artisan storage:link
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: "Palsa POS"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://palsa-pos.onrender.com
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: palsa-pos-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: palsa-pos-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: palsa-pos-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: palsa-pos-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: palsa-pos-db
          property: password
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: MAIL_MAILER
        value: log

  - type: pserv
    name: palsa-pos-db
    env: mysql
    plan: starter
    disk:
      name: palsa-pos-data
      mountPath: /var/lib/mysql
      sizeGB: 1